#!/bin/bash
# =============================================================================
# Smart Pre-commit Hook — CODEBASE_INDEX.yaml Enforcement
# Generated by HubLLM project scaffold
# =============================================================================

INDEX="harness/CODEBASE_INDEX.yaml"
ERRORS=""
WARNINGS=""

# Get staged code files
CODE_FILES=$(git diff --cached --name-only | grep -E "^src/" | grep -v "__pycache__" | grep -v ".pyc")

# Exit early if no code files changed
[ -z "$CODE_FILES" ] && exit 0

# Check if index exists
if [ ! -f "$INDEX" ]; then
    echo ""
    echo "COMMIT BLOCKED — $INDEX not found."
    echo "Create the index file, then re-commit."
    echo "Bypass: git commit --no-verify"
    echo ""
    exit 1
fi

# Check if index is staged
INDEX_STAGED=$(git diff --cached --name-only | grep "$INDEX")
if [ -z "$INDEX_STAGED" ]; then
    echo ""
    echo "COMMIT BLOCKED — Code files changed but $INDEX was NOT staged!"
    echo ""
    echo "Changed code files:"
    echo "$CODE_FILES" | head -10
    echo ""
    echo "Stage the index: git add $INDEX"
    echo "Bypass: git commit --no-verify (only for non-code commits)"
    echo ""
    exit 1
fi

# 1. Check each changed file has an entry in the index
for f in $CODE_FILES; do
    BASENAME=$(basename "$f")
    if ! grep -q "$BASENAME" "$INDEX" 2>/dev/null; then
        LINES=$(wc -l < "$f" 2>/dev/null || echo "?")
        ERRORS="${ERRORS}  - $f (new file, ${LINES} lines)\n"
    fi
done

# 2. Check line counts match for changed files that ARE in the index
for f in $CODE_FILES; do
    BASENAME=$(basename "$f")
    INDEX_LINES=$(grep -A2 "$BASENAME" "$INDEX" 2>/dev/null | grep "lines:" | head -1 | grep -oE "[0-9]+")
    if [ -n "$INDEX_LINES" ] && [ -f "$f" ]; then
        ACTUAL_LINES=$(wc -l < "$f")
        if [ "$INDEX_LINES" != "$ACTUAL_LINES" ]; then
            WARNINGS="${WARNINGS}  - $f: index says ${INDEX_LINES}, actual is ${ACTUAL_LINES}\n"
        fi
    fi
done

# 3. Check for duplicate entries
for f in $CODE_FILES; do
    BASENAME=$(basename "$f")
    COUNT=$(grep -c "$BASENAME" "$INDEX" 2>/dev/null || echo 0)
    if [ "$COUNT" -gt 1 ]; then
        WARNINGS="${WARNINGS}  - $BASENAME appears ${COUNT} times in index\n"
    fi
done

# Block on missing entries, warn on mismatches
if [ -n "$ERRORS" ]; then
    echo ""
    echo "COMMIT BLOCKED — Index issues found:"
    echo ""
    echo "Missing from index:"
    echo -e "$ERRORS"
    if [ -n "$WARNINGS" ]; then
        echo "Line count mismatch / duplicates:"
        echo -e "$WARNINGS"
    fi
    echo "Fix these in $INDEX, then re-commit."
    echo "Bypass: git commit --no-verify (only for non-code commits)"
    echo ""
    exit 1
fi

if [ -n "$WARNINGS" ]; then
    echo ""
    echo "WARNING — Index issues (non-blocking):"
    echo -e "$WARNINGS"
    echo ""
fi
